### ISSUE TITLE
Add class path prefix

### ISSUE THREAD

**Issue by st-schneider** [TheNouillet/symfony-vscode#37]
In the composer.json there is an autoload config that makes it look like all classes have their root in the root folder when it actually is in src/ folder. This disables the jumping to the classes from the view.
Either read such configs from the composer.json or add an option to add a prefix for class file resolution please.

**Comment by st-schneider** [comment]
Can you save the psr-0/4 from autoload as well and add it to the class resolution strategy?
composerObj.autoload['psr-0']
composerObj.autoload['psr-4']
https://github.com/TheNouillet/symfony-vscode/blob/9f7318751c0cc2c74d0dfcc4bd8adbf68636740b/src/symfony/ComposerJSON.ts#L17

**Comment by TheNouillet** [comment]
Hello,

I'm having trouble understanding the problem. Right now, here how it works :

- All files with a *.php extension are parsed.
- If they have a `namespace` instruction, then the class of this file will be prepended by the namespace in the class collection.
- The class in itself is parsed, with its name and its methods

So the "PHP parsing" part of the extension doesn't rely on the `composer.json` file. That said, there is a bug which prevents the "Go to service definition" functionnality to work correctly, because of an issue with the cache system (services, routes, parameters and classes are cached, so that the next startup of your project on VSCode is faster). This bug will be fixed in the next release. For now, you can reindex PHP files with the `Reindex PHP classes` command to bypass the faulty cache system.

Please let me know if I misunderstood the problem.

**Comment by st-schneider** [comment]
You seem to be right, after reindexing the classes could be resolved. I had the problem the the class name was something like Something\Else but it was in the src folder so it would be something like /src/Something/Else but it would always state Something/Else could not be found, and I assumed that the psr thing would be the cause.

**Comment by st-schneider** [comment]
I seem to still have that problem for some classes though

**Comment by st-schneider** [comment]
Does the extension also use the available exclude options from "files.exclude" option when indexing?
